runtime: java11
env: standard

instance_class: F4
service: backend

handlers:
  - url: /.*
    script: this field is required, but ignored

automatic_scaling:
    min_instances: 2
    max_instances: 4
