CREATE TABLE tbl_Users_Credentials (
login VARCHAR(30) NOT NULL PRIMARY KEY,
password VARCHAR(254) NOT NULL,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
created_by VARCHAR(30),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
updated_by VARCHAR(30)
);

CREATE TABLE tbl_Users (
login VARCHAR(30) NOT NULL,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
created_by VARCHAR(30),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
updated_by VARCHAR(30),
PRIMARY KEY (login),
FOREIGN KEY (login) REFERENCES tbl_Users_Credentials(login)
);

ALTER TABLE tbl_Users
ADD COLUMN full_name VARCHAR(70)
GENERATED ALWAYS AS (`first_name` + " " + `last_name`) VIRTUAL;

CREATE TABLE tbl_Steps (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
sort_order INT(6) UNSIGNED NOT NULL,
name VARCHAR(30) NOT NULL,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
created_by VARCHAR(30),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
updated_by VARCHAR(30)
);

CREATE TABLE tbl_Issues (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
closed TIMESTAMP,
name VARCHAR(30) NOT NULL,
description VARCHAR(254) NOT NULL,
importance INT(6) UNSIGNED NOT NULL,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
created_by VARCHAR(30),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
updated_by VARCHAR(30)
);

CREATE TABLE tbl_Issues_Steps (
issue_id INT(6) UNSIGNED NOT NULL,
responsible VARCHAR(30) NOT NULL,
step_id INT(6) UNSIGNED NOT NULL,
comment VARCHAR(254) NOT NULL,
completed TIMESTAMP,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
created_by VARCHAR(30),
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
updated_by VARCHAR(30),
PRIMARY KEY (issue_id, responsible, step_id),
FOREIGN KEY (issue_id) REFERENCES tbl_Issues(id) ON DELETE CASCADE,
FOREIGN KEY (responsible) REFERENCES tbl_Users_Credentials(login),
FOREIGN KEY (step_id) REFERENCES tbl_Steps(id)
);